### ISSUE TITLE
Frontmatter is missing when adding a new post

### ISSUE THREAD

**Issue by dabonnestor** [itsnwa/gridsome-forestry-starter#7]
Hi. When adding a new blog post on forestry the front matter wasn't added on the markdown file. This is what I'm trying to add a new post.

![post](https://user-images.githubusercontent.com/22286294/57970398-690bd200-79b3-11e9-867b-fda53a67e9d5.JPG)

**Comment by etiennemarais** [comment]
Also experiencing the same thing. Every time I update my forestry post, it resets the data part at the top like in the above example. Even though I set the template with the correct fields Please assist?

**Comment by DirtyF** [comment]
We fixed a related bug in Forestry earlier this day, do you still experience this?

**Comment by dabonnestor** [comment]
@etiennemarais @DirtyF Forestry already made a fix for this issue. I did some test and its working now. I will now close this issue.
